### ISSUE TITLE
Suffixes to resolve filename collisions

### ISSUE THREAD

**Issue by bwprice** [NaturalHistoryMuseum/gouda#14]
When presented with two or more images with the same barcode (ie labels flipped / different specimen views) the renaming based on the barcode value should include the addition of a suffix to the file name (eg. barcode1.jpg......barcode1_2.jpg.......barcode1_3.jpg).

**Comment by quicklizard99** [comment]
Add an option to implement this behaviour. Default behaviour should be to raise an error if the destination file already exists.

**Comment by quicklizard99** [comment]
This feature also requested by Henry Engledow, Botanic Garden Meise.
